//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientosConMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Numero_Carnet { get; set; }
        public string Carrera { get; set; }
        public string Género { get; set; }
    }
}
