//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientosConMenu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="de ley se necsita nombre. ¡puchis!")]
        [Display(Name ="Nombre del Cliente")]
        public string Nombre { get; set; }
        [Required]
        public string Dirección { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string Teléfono { get; set; }
    }
}